[package]
name = "mario"
version = "0.1.0"
authors = ["mantou <709922234@qq.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
actix-web = "0.7.19"
futures = "0.1.27"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
