[package]
name = "mario"
version = "0.1.0"
authors = ["mantou <709922234@qq.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.1.12", features = ["derive", "env"] }
once_cell = "1.10.0"
json = "0.12.4"
actix-web = "1.0.0"
futures = "0.1.27"
